name: WebApp

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webappimage
    container_name: WebApp
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/home
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
